version: '3'
services:
  nestjs-app:
    image: biojj/cost-spreadsheet-management-back:1.0
    container_name: cost-spreadsheet-management-back
    ports:
      - 3000:3000
    networks:
      - docker-cost
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: roo123
      POSTGRES_DB: cost-spreadsheet
      JWT_SECRET_KEY: Lr9UAevTgV7TnHLSHp0/9L5MaU4323AfPcqSjm+PZ3w=
      API_PYTHON: python-app
      API_PYTHON_PORT: 5000

  python-app:
    image: biojj/cost-spreadsheet-process-back:1.0
    container_name: cost-spreadsheet-process-back
    ports:
      - "5000:5000"
    networks:
      - docker-cost

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: roo123
      POSTGRES_DB: cost-spreadsheet
    ports:
      - "5432:5432"
    networks:
      - docker-cost

networks:
  docker-cost:
    driver: bridge
